export default [{
    menuTitle:'缴费记录',
    menuIcon:'payRecord',
     pageTable:'payRecord',
},{
    menuTitle:'跟踪回访',
    menuIcon:'callbackRecord',
    pageTable:'callbackRecord',
},{
    menuTitle:'排课记录',
    menuIcon:'courseRecord',
    pageTable:'courseRecordclasses',
},{
    menuTitle:'考勤记录',
    menuIcon:'salaryRecord',
    pageTable:'classes1',
},{
    menuTitle:'请假记录',
    menuIcon:'lessonleaveRecord',
     pageTable:'lessonleaveRecord',
},{
    menuTitle:'赛事记录',
    menuIcon:'eventsRecord',
     pageTable:'eventsRecord',
}]