export default [{
    menuTitle:'缴费记录',
    menuIcon:'payRecord',
     pageTable:'pay',
},{
    menuTitle:'跟踪回访',
    menuIcon:'callbackRecord',
    pageTable:'inquiry',
},{
    menuTitle:'排课记录',
    menuIcon:'courseRecord',
     pageTable:'arrange',
},{
    menuTitle:'考勤记录',
    menuIcon:'salaryRecord',
     pageTable:'attendance',
},{
    menuTitle:'请假记录',
    menuIcon:'lessonleaveRecord',
     pageTable:'leaves',
},{
    menuTitle:'赛事记录',
    menuIcon:'eventsRecord',
     pageTable:'recording',
}]